# Generated by Django 3.1 on 2020-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
