# Generated by Django 3.1 on 2020-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0002_material_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio_base', models.FloatField()),
                ('actividades', models.ManyToManyField(to='configuracion.Actividad')),
            ],
        ),
    ]
